name-template: $NEXT_MINOR_VERSION
tag-template: $NEXT_MINOR_VERSION
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
categories:
  - title: Endpoints Update
    labels:
      - 'endpoints'

  - title: Bug Fixing
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: Patch Changes
    labels:
      - 'patch'

template: |
  ## Changes
  $CHANGES